GitHub library build workflow

diff --git a/.github/workflows/LibraryBuildWithSteps.yml b/.github/workflows/LibraryBuildWithSteps.yml
--- a/.github/workflows/LibraryBuildWithSteps.yml
+++ b/.github/workflows/LibraryBuildWithSteps.yml
@@ -1,9 +1,22 @@
+# LibraryBuildWithSteps.yml
+# Github workflow script to test compile all examples of an Arduino library repository.
+#
+# Copyright (C) 2020  Armin Joachimsmeyer
+# https://github.com/ArminJo/Github-Actions
+#
 # Before being able to push to my .github\workflows directories,
 # I had to create a new personal token with workflow enabled at https://github.com/settings/tokens
 
 # This is the name of the workflow, visible on GitHub UI.
-name: LibraryBuild
-on: [push]
+name: LibraryBuildWithSteps
+on:  
+  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
+    paths:
+    - '**.ino'
+    - '**.cpp'
+    - '**.h'
+    - '**LibraryBuildWithSteps.yml'
+  pull_request:
 
 jobs:
   build:
@@ -12,12 +25,10 @@ jobs:
     runs-on: ubuntu-latest # I picked Ubuntu to use shell scripts.
 
     env:
-      # Space separated list without double quotes around the list. 
-      # If you need a library with a space in its name, like Adafruit NeoPixel or Adafruit INA219, you must use double quotes
-      # around the name and have at least 2 entries, where the first must be without double quotes! You may use Servo as dummy entry.
-      REQUIRED_LIBRARIES:
+      # Comma separated list without double quotes around the list. 
+      REQUIRED_LIBRARIES: ATtinySerialOut
 
-      # Output colors
+      # Global color definitions for output colors
       RED: '\033[0;31m'
       GREEN: '\033[0;32m'
       YELLOW: '\033[1;33m'
@@ -32,7 +43,7 @@ jobs:
         # arduino:sam:arduino_due_x, arduino:samd:arduino_zero_native"
         # ATTinyCore:avr:attinyx5:chip=85,clock=1internal, digistump:avr:digispark-tiny, digistump:avr:digispark-pro
         # STM32:stm32:GenF1:pnum=BLUEPILL_F103C8
-        #esp8266:esp8266:huzzah:eesz=4M3M,xtal=80, esp32:esp32:featheresp32:FlashFreq=80
+        # esp8266:esp8266:huzzah:eesz=4M3M,xtal=80, esp32:esp32:featheresp32:FlashFreq=80
         # You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace
         #############################################################################################################
         arduino-boards-fqbn:
@@ -40,20 +51,16 @@ jobs:
           - digistump:avr:digispark-tiny1
           - ATTinyCore:avr:attinyx5:chip=85,clock=1internal
 
-        # Choose the right platform for the boards we want to test. (maybe in the future Arduino will automatically do this for you).
-        # This works like this: when the fqbn is "arduino:avr:uno" the variable `platform` is set to "arduino:avr".
-        # Just take the first 2 token of the fqbn - this cannot be automatically done by GitHub workflow :-(
-        # You may exclude specific examples for a board with examples-exclude: Use a space separated list.
+        # Specify parameters for each board.
+        # With examples-exclude you may exclude specific examples for a board. Use a comma separated list.
         #############################################################################################################
         include:
-          - arduino-boards-fqbn: arduino:avr:uno
-            platform: arduino:avr
-
           - arduino-boards-fqbn: digistump:avr:digispark-tiny1  # ATtiny85 board @1 MHz
-            platform: digistump:avr
+            platform-url: http://digistump.com/package_digistump_index.json
+            examples-exclude: Blink
 
           - arduino-boards-fqbn: ATTinyCore:avr:attinyx5:chip=85,clock=1internal
-            platform: ATTinyCore:avr
+            platform-url: http://drazzy.com/package_drazzy.com_index.json
 
       # Do not cancel all jobs / architectures if one job fails
       fail-fast: false
@@ -64,6 +71,10 @@ jobs:
       # First of all, we clone the repo using the `checkout` action.
       - name: Checkout
         uses: actions/checkout@master
+
+##################################################################################################
+# This fixed script section can be replaced by the action ArminJo/arduino-test-compile@master
+##################################################################################################
 
       # We use the `arduino/setup-arduino-cli` action to install and
       # configure the Arduino CLI on the system.
@@ -79,33 +90,52 @@ jobs:
         env:
           FQBN: ${{ matrix.arduino-boards-fqbn }}
         run: |
-          arduino-cli core update-index
-          if [ "${{  matrix.platform }}" == "" ]; then echo -e ""$RED"ERROR: platform missing for board ${FQBN%|*}. Check your matrix.includes entries"; exit 1; fi
-          if [[ ${{  matrix.platform }} != *"arduino"* && ! -f ./arduino-cli.yaml ]]; then echo -e ""$RED"Non Arduino platform ${{  matrix.platform }} requested, but file arduino-cli.yaml is missing."; exit 1; fi
-          arduino-cli core install ${{ matrix.platform }} # for each job / board one platform is installed
-          arduino-cli board listall
-          if [ ${{  matrix.platform }} == "esp32:esp32" ]; then pip install pyserial; fi
+          arduino-cli version
+          # Compute platform value and check for platform-url parameter
+          remainder=${FQBN#*:}; PLATFORM=${FQBN%%:*}:${remainder%%:*}
+          if [[ ${PLATFORM} != *"arduino"* && ! (-f ./arduino-cli.yaml || "${{ matrix.platform-url }}" != ""  ) ]]; then
+            echo "::error::Non Arduino platform ${PLATFORM} requested, but \"platform-url\" parameter and file arduino-cli.yaml are missing."; exit 1
+          fi
+          if [[ "${{ matrix.platform-url }}" != "" ]]; then
+            arduino-cli core update-index --additional-urls "${{ matrix.platform-url }}"
+            echo -e "arduino-cli core install $PLATFORM --additional-urls \"${{ matrix.platform-url }}\""
+            arduino-cli core install ${PLATFORM} --additional-urls "${{ matrix.platform-url }}" # for each job / board one platform is installed
+          else
+            arduino-cli core update-index
+            echo "arduino-cli core install $PLATFORM"
+            arduino-cli core install ${PLATFORM} # for each job / board one platform is installed
+          fi
+          if [ ${PLATFORM} == "esp32:esp32" ]; then pip install pyserial; fi
 
       - name: List installed boards with their FQBN
         run: |
           arduino-cli board listall
-          # ls -l $HOME/.arduino15/packages/ # I see only arduino and one of the Attiny cores but not all 3 together
-          # echo -e HOME=\"$HOME\" # /home/runner
-          # echo PWD=$PWD # /home/runner/work/Github-Actions-Test/Github-Actions-Test
-          # which arduino-cli # /opt/hostedtoolcache/arduino-cli/0.9.0/x64/arduino-cli
 
       - name: Install libraries
-        run: if [[ "$REQUIRED_LIBRARIES" != "" ]]; then arduino-cli lib install ${{ env.REQUIRED_LIBRARIES }}; fi
-
-      # Finally, we compile the sketch, using the FQBN that was set in the build matrix.
+        run: |
+          if [[ -z $REQUIRED_LIBRARIES ]]; then
+            echo "No additional libraries to install"
+          else
+            echo "Install libraries $REQUIRED_LIBRARIES"
+            # Support comma separated library list
+            BACKUP_IFS="$IFS"
+            IFS=$','
+            declare -a REQUIRED_LIBRARIES_ARRAY=( $REQUIRED_LIBRARIES )
+            IFS="$BACKUP_IFS"            
+            declare -p REQUIRED_LIBRARIES_ARRAY # print properties of REQUIRED_LIBRARIES_ARRAY
+            echo "Install libraries list ${REQUIRED_LIBRARIES_ARRAY[@]}"
+            arduino-cli lib install "${REQUIRED_LIBRARIES_ARRAY[@]}"
+          fi
+          
+      # Finally, we compile all examples, using all parameter given in the build matrix.
       - name: Compile all examples
         env:
           FQBN: ${{ matrix.arduino-boards-fqbn }}
           BUILD_PROPERTIES: ${{ toJson(matrix.examples-build-properties) }}
         run: |
+          # If matrix.examples-build-properties are specified, create an associative shell array
           BUILD_PROPERTIES=${BUILD_PROPERTIES#\{} # remove "{"
-          # if matrix.examples-build-properties are specified, create an associative shell array
-          if [[ $BUILD_PROPERTIES != "null" ]]; then declare -A PROP_MAP="( $(echo $BUILD_PROPERTIES | sed -E 's/"(\w*)": *([^,}]*)[,}]/\[\1\]=\2/g' ) )"; fi
+          if [[ $BUILD_PROPERTIES != "null" ]]; then declare -A PROP_MAP="( $(echo $BUILD_PROPERTIES | sed -E 's/"(\w*)": *([^,}]*)[,}]/\[\1\]=\2/g' ) )"; else declare -A PROP_MAP=( [dummy]=dummy ); fi
           echo -e "Compiling examples for board ${{ matrix.arduino-boards-fqbn }} \n"
           EXAMPLES=($(find . -name "*.ino"))
           for example in "${EXAMPLES[@]}"; do # Loop over all example directories
@@ -119,6 +149,7 @@ jobs:
               build_stdout=$(arduino-cli compile --verbose --warnings all --fqbn ${FQBN%|*} --build-properties compiler.cpp.extra_flags="${PROP_MAP[$EXAMPLE_NAME]}" $(dirname $example) 2>&1);
               if [ $? -ne 0 ]; then
                 echo -e ""$RED"\xe2\x9c\x96" # If ok output a green checkmark else a red X and the command output.
+                echo "::error::Compile of  $EXAMPLE_NAME ${PROP_MAP[$EXAMPLE_NAME]} failed"
                 exit_code=1
                 echo -e "$build_stdout \n"
               else
